[package]
authors = ["Joshua Holmer <jholmer.in@gmail.com>"]
categories = [
    "command-line-utilities",
    "compression",
]
description = "A lossless PNG compression optimizer"
documentation = "https://docs.rs/oxipng"
exclude = [
    "tests/*",
    "bench/*",
]
homepage = "https://github.com/shssoichiro/oxipng"
license = "MIT"
name = "oxipng"
repository = "https://github.com/shssoichiro/oxipng"
version = "2.0.2"

[badges]
travis-ci = { repository = "shssoichiro/oxipng", branch = "master" }
maintenance = { status = "actively-developed" }

[[bin]]
doc = false
name = "oxipng"
path = "src/main.rs"
required-features = ["binary"]

[dependencies]
bit-vec = "^0.5.0"
byteorder = "^1.0.0"
crc = "^1.2.0"
itertools = "^0.7.7"
num_cpus = "^1.0.0"
zopfli = "^0.3.4"
miniz_oxide = "0.1.2"

[dependencies.rayon]
optional = true
version = "^1.0.0"

[dependencies.clap]
optional = true
version = "^2.10.0"

[dependencies.wild]
optional = true
version = "1.0.1"

[dependencies.cloudflare-zlib-sys]
optional = true
version = "^0.1.2"

[dependencies.image]
default-features = false
features = ["png_codec"]
version = "^0.19.0"

[features]
binary = [
    "clap",
    "wild",
]
default = ["binary", "parallel"]
parallel = ["rayon"]
cfzlib = ["cloudflare-zlib-sys"]
dev = [
    "nightly-binary",
]
nightly = ["cfzlib"]
nightly-binary = [
    "binary",
    "nightly",
]

[lib]
name = "oxipng"
path = "src/lib.rs"
[profile.dev]
opt-level = 2
