[package]
authors = ["Joshua Holmer <jholmer.in@gmail.com>"]
categories = ["command-line-utilities", "compression"]
description = "A lossless PNG compression optimizer"
documentation = "https://docs.rs/oxipng"
exclude = ["tests/*", "bench/*"]
homepage = "https://github.com/shssoichiro/oxipng"
license = "MIT"
name = "oxipng"
repository = "https://github.com/shssoichiro/oxipng"
version = "0.14.4"

[lib]
name = "oxipng"
path = "src/lib.rs"

[[bin]]
doc = false
name = "oxipng"
path = "src/main.rs"

[dependencies]
bit-vec = "^0.4.2"
byteorder = "^1.0.0"
crc = "^1.2.0"
itertools = "^0.5.7"
libc = "^0.2.4"
miniz-sys = "^0.1.7"
num_cpus = "^1.0.0"
rayon = "^0.6.0"
zopfli = "^0.3.4"

[dependencies.clap]
optional = true
version = "^2.10.0"

[dependencies.clippy]
optional = true
version = ">=0.0.85"

[dependencies.image]
default-features = false
features = ["png_codec"]
version = "^0.12.0"

[dependencies.regex]
optional = true
version = "^0.2.0"

[features]
default = ["binary"]
binary = ["clap", "regex"]
nightly = ["rayon/unstable"]
nightly-binary = ["binary", "nightly", "regex/simd-accel"]
dev = ["nightly-binary", "clippy"]

[profile.dev]
opt-level = 2
