[package]
authors = ["Joshua Holmer <jholmer.in@gmail.com>"]
categories = [
    "command-line-utilities",
    "compression",
]
description = "A lossless PNG compression optimizer"
documentation = "https://docs.rs/oxipng"
edition = "2018"
exclude = [
    "tests/*",
    "bench/*",
]
homepage = "https://github.com/shssoichiro/oxipng"
license = "MIT"
name = "oxipng"
repository = "https://github.com/shssoichiro/oxipng"
version = "2.2.1"

[badges]
travis-ci = { repository = "shssoichiro/oxipng", branch = "master" }
maintenance = { status = "actively-developed" }

[[bin]]
doc = false
name = "oxipng"
path = "src/main.rs"
required-features = ["binary"]

[dependencies]
bit-vec = "^0.5.0"
byteorder = "^1.0.0"
crc = "^1.2.0"
itertools = "^0.8.0"
num_cpus = "^1.0.0"
zopfli = "^0.4.0"
miniz_oxide = "0.2.0"
rgb = "0.8.11"

[dependencies.rayon]
optional = true
version = "^1.0.0"

[dependencies.clap]
optional = true
version = "^2.10.0"

[dependencies.wild]
optional = true
version = "2.0.0"

[target.'cfg(any(target_arch = "x86_64", target_arch = "aarch64"))'.dependencies]
cloudflare-zlib = "^0.2.2"

[dependencies.image]
default-features = false
features = ["png_codec"]
#FIXME: Use upstream version when 0.22 is released
#Contains bugfix for issues 167 and 168
#version = "^0.21.0"
git = "https://github.com/PistonDevelopers/image"
rev = "41dfbae"

[features]
binary = [
    "clap",
    "wild",
]
default = ["binary", "parallel"]
parallel = ["rayon"]

[lib]
name = "oxipng"
path = "src/lib.rs"
[profile.dev]
opt-level = 2
[profile.release]
lto = true
