[package]
authors = ["Joshua Holmer <jholmer.in@gmail.com>"]
categories = [
    "command-line-utilities",
    "compression",
]
description = "A lossless PNG compression optimizer"
documentation = "https://docs.rs/oxipng"
edition = "2018"
exclude = [
    "tests/*",
    "bench/*",
]
homepage = "https://github.com/shssoichiro/oxipng"
license = "MIT"
name = "oxipng"
repository = "https://github.com/shssoichiro/oxipng"
build = "build.rs"
version = "4.0.2"

[badges]
travis-ci = { repository = "shssoichiro/oxipng", branch = "master" }
maintenance = { status = "actively-developed" }

[[bin]]
doc = false
name = "oxipng"
path = "src/main.rs"
required-features = ["binary"]

[dependencies]
bit-vec = "^0.6.3"
byteorder = "^1.0.0"
crc = "^1.2.0"
itertools = "^0.9.0"
zopfli = { version = "^0.4.0", optional = true }
miniz_oxide = "0.4"
rgb = "0.8.25"
indexmap = "1.6.1"
libdeflater = { version = "0.7.1", optional = true }
log = "0.4.11"
stderrlog = { version = "0.5.0", optional = true }
crossbeam-channel = "0.5.0"
filetime = "0.2.13"

[dependencies.rayon]
optional = true
version = "^1.5.0"

[dependencies.clap]
optional = true
version = "^2.33.3"

[dependencies.wild]
optional = true
version = "2.0.4"

[dependencies.image]
default-features = false
features = ["png"]
version = "0.23"

[target.'cfg(any(target_arch = "x86_64", target_arch = "aarch64"))'.dependencies.cloudflare-zlib]
features = ["arm-always"]
version = "^0.2.2"

[build-dependencies]
rustc_version = "0.3"

[features]
binary = [
    "clap",
    "wild",
    "stderrlog",
]
default = ["binary", "parallel", "libdeflater", "zopfli"]
parallel = ["rayon", "indexmap/rayon"]

[lib]
name = "oxipng"
path = "src/lib.rs"
[profile.dev]
opt-level = 2
[profile.release]
lto = "thin"
